version: '3.8' # Specify the version of the Docker Compose file format

services:
  postgres:
    image: postgres:16
    container_name: hongo_postgres
    restart: always
    environment:
      TZ: Asia/Ho_Chi_Minh
      PGTZ: Asia/Ho_Chi_Minh
      POSTGRES_USER: nihongo_user
      POSTGRES_PASSWORD: nihongo_password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
