version: '3.8' # Specify the version of the Docker Compose file format

services:
  postgres:
    image: postgres:16
    container_name: hongo_postgres
    restart: always
    environment:
      TZ: Asia/Ho_Chi_Minh
      PGTZ: Asia/Ho_Chi_Minh
      POSTGRES_USER: nihongo_user
      POSTGRES_PASSWORD: nihongo_password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.1
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 200M
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"
      
    networks:
      - l4l

volumes:
  postgres_data:
  kafka-data:

networks:
  l4l:
    driver: bridge