server:
  port: 8080

application:
  backend-url: http://localhost:8080/api/v1/auth
  frontend-url: http://localhost:4200
  security:
    jwt:
      secrets: 7128ba29ccf93f7ea1188b0134db46f4f87b46f1d56766e3f7fef6197bd286c1
      expirations:
        access-token: 3600000
        refresh-token: 604800000

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service_db
    username: nihongo_user
    password: nihongo_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID:your-client-id.apps.googleusercontent.com}
    client-secret: ${GOOGLE_CLIENT_SECRET:your-client-secret}
    redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/api/auth/oauth/google/callback}
    scope: openid email profile

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
  httpclient:
    enabled: true2
    max-connections: 200
    max-connections-per-route: 50

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %highlight(%-5level) %clr([%thread]){cyan} %clr(%logger{36}){yellow} %clr([%file:%line]){magenta} - %msg%n"
