server:
  port: 8081

progress-service:
  base-url: http://progress-service

resilience4j:
  circuitbreaker:
    instances:
      progressService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true
  timelimiter:
    instances:
      progressService:
        timeout-duration: 2s

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learning_service_db
    username: nihongo_user
    password: nihongo_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

app:
  youtube:
    api-key: AIzaSyCUrRKVExQiB9aMIRnqidkW4m-o4luRbR0

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %highlight(%-5level) %clr([%thread]){cyan} %clr(%logger{36}){yellow} %clr([%file:%line]){magenta} - %msg%n"
