server:
  port: 8082

spring:
  mongodb:
    # uri: mongodb://vsung2608:TzJRLiAJUIGvMWwg@127.0.0.1:27017/notification-service?authSource=admin
    uri: mongodb+srv://vsung2608:TzJRLiAJUIGvMWwg@l4lcluster.ri4oflp.mongodb.net/notification_service?appName=l4lcluster&retryWrites=true&w=majority
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group 
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:vsung2608@gmail.com}
    password: ${MAIL_PASSWORD:cnbphwikvtophphn}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
app:
  mail:
    from: vsung2608@gmail.com
  frontend:
    url: http://localhost:4200
  backend:
    url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %highlight(%-5level) %clr([%thread]){cyan} %clr(%logger{36}){yellow} %clr([%file:%line]){magenta} - %msg%n"
